<?php
declare(strict_types=1);

// Cie10 SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

Cie10Utility::setRegistrar(function (Cie10Utility $u): void {
    $u->clean = [Cie10Clean::class, 'call'];
    $u->done = [Cie10Done::class, 'call'];
    $u->make_error = [Cie10MakeError::class, 'call'];
    $u->feature_add = [Cie10FeatureAdd::class, 'call'];
    $u->feature_hook = [Cie10FeatureHook::class, 'call'];
    $u->feature_init = [Cie10FeatureInit::class, 'call'];
    $u->fetcher = [Cie10Fetcher::class, 'call'];
    $u->make_fetch_def = [Cie10MakeFetchDef::class, 'call'];
    $u->make_context = [Cie10MakeContext::class, 'call'];
    $u->make_options = [Cie10MakeOptions::class, 'call'];
    $u->make_request = [Cie10MakeRequest::class, 'call'];
    $u->make_response = [Cie10MakeResponse::class, 'call'];
    $u->make_result = [Cie10MakeResult::class, 'call'];
    $u->make_point = [Cie10MakePoint::class, 'call'];
    $u->make_spec = [Cie10MakeSpec::class, 'call'];
    $u->make_url = [Cie10MakeUrl::class, 'call'];
    $u->param = [Cie10Param::class, 'call'];
    $u->prepare_auth = [Cie10PrepareAuth::class, 'call'];
    $u->prepare_body = [Cie10PrepareBody::class, 'call'];
    $u->prepare_headers = [Cie10PrepareHeaders::class, 'call'];
    $u->prepare_method = [Cie10PrepareMethod::class, 'call'];
    $u->prepare_params = [Cie10PrepareParams::class, 'call'];
    $u->prepare_path = [Cie10PreparePath::class, 'call'];
    $u->prepare_query = [Cie10PrepareQuery::class, 'call'];
    $u->graphql_body = [Cie10Graphql::class, 'body'];
    $u->graphql_errors = [Cie10Graphql::class, 'errors'];
    $u->result_basic = [Cie10ResultBasic::class, 'call'];
    $u->result_body = [Cie10ResultBody::class, 'call'];
    $u->result_headers = [Cie10ResultHeaders::class, 'call'];
    $u->transform_request = [Cie10TransformRequest::class, 'call'];
    $u->transform_response = [Cie10TransformResponse::class, 'call'];
});
